name: دانلود یوتیوب و ذخیره فایل

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'لینک ویدیو یوتیوب'
        required: true
      chat_id:
        description: 'Chat ID تلگرام'
        required: true
      message_id:
        description: 'Message ID تلگرام'
        required: false

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: نصب yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp ffmpeg

      - name: دانلود ویدیو با کوکی
        run: |
          URL="${{ github.event.inputs.youtube_url }}"
          echo "در حال دانلود: $URL"
          
          yt-dlp \
            --cookies <(echo "${{ secrets.YBE_COOKS }}") \
            -f "best[height<=720]/best" \
            --merge-output-format mp4 \
            --no-playlist \
            --retries 4 \
            -o "video_%(title)s_%(id)s.mp4" \
            "$URL"

      - name: آماده‌سازی نام فایل
        id: filename
        run: echo "filename=$(ls *.mp4 | head -n 1)" >> $GITHUB_OUTPUT

      - name: آپلود Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: "*.mp4"
          retention-days: 3

      - name: اطلاع‌رسانی به کاربر
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ github.event.inputs.chat_id }} \
            -d reply_to_message_id=${{ github.event.inputs.message_id }} \
            -d text="✅ دانلود انجام شد!📄 نام فایل: ${{ steps.filename.outputs.filename }}"
