name: تست دانلود پیشرفته

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3
        with:
          aria2: true

      - name: دانلود
        run: |
          yt-dlp \
            --extractor-args "youtube:player_client=android,web" \
            -f "best[height<=720]/best" \
            --merge-output-format mp4 \
            --no-playlist \
            --retries 10 \
            --sleep-interval 5 \
            --sleep-requests 2.5 \
            "${{ github.event.inputs.youtube_url }}"
